services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: root