ARG NODE_VERSION=22.14.0
ARG NODEMON_VERSION=3.0.1
FROM node:${NODE_VERSION}-slim
#FROM node:${NODE_VERSION}-alpine

ENV PORT=3000

RUN apt update && apt install -y curl

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

USER node

HEALTHCHECK --interval=20s --timeout=5s --start-period=5s --retries=3 CMD [ "curl", "-f", "http://localhost:3000" ]

EXPOSE 3000

CMD npm start
